version: '3.8'

services:
  phone-control-web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./Software:/app/Software
    environment:
      - NODE_ENV=production
      - PORT=3000
    depends_on:
      - phone-control-api
    networks:
      - phone-control-network

  phone-control-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./src/api:/app/src/api
      - ./Software:/app/Software
      - /dev/bus/usb:/dev/bus/usb
    environment:
      - PYTHONPATH=/app
      - API_HOST=0.0.0.0
      - API_PORT=8000
    privileged: true
    devices:
      - /dev/bus/usb:/dev/bus/usb
    networks:
      - phone-control-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - phone-control-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - phone-control-web
      - phone-control-api
    networks:
      - phone-control-network

volumes:
  redis_data:

networks:
  phone-control-network:
    driver: bridge